/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package foot;

/**
 *
 * @author mooneswar.ramburrun
 */
public class Foot extends javax.swing.JFrame {

    /**
     * Creates new form Foot
     */
    public Foot() {
        initComponents();
        pf = new PanelFoot();
        pane.add(pf);
        setLocation(250,150);
        recommencer.setEnabled(false);
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane = new javax.swing.JPanel();
        haut = new javax.swing.JButton();
        bas = new javax.swing.JButton();
        patate = new javax.swing.JButton();
        recommencer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(575, 320));
        setResizable(false);

        pane.setPreferredSize(new java.awt.Dimension(548, 222));
        pane.setLayout(new java.awt.GridLayout(1, 0));

        haut.setText("haut");
        haut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haut(evt);
            }
        });

        bas.setText("bas");
        bas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bas(evt);
            }
        });

        patate.setText("patate tout droit ");
        patate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patate(evt);
            }
        });

        recommencer.setText("recommencer");
        recommencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recommencer(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(haut)
                .addGap(59, 59, 59)
                .addComponent(bas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(patate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(recommencer)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pane, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pane, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patate)
                    .addComponent(bas)
                    .addComponent(haut)
                    .addComponent(recommencer))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void haut(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haut
       pf.haut();
       haut.setEnabled(false);
       bas.setEnabled(false);
       patate.setEnabled(false);
       recommencer.setEnabled(true);
    }//GEN-LAST:event_haut

    private void bas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bas
        pf.bas();
       haut.setEnabled(false);
       bas.setEnabled(false);
       patate.setEnabled(false);
       recommencer.setEnabled(true);
    }//GEN-LAST:event_bas

    private void patate(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patate
        pf.patate();
        haut.setEnabled(false);
       bas.setEnabled(false);
       patate.setEnabled(false);
        recommencer.setEnabled(true);
    }//GEN-LAST:event_patate

    private void recommencer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recommencer
        // TODO add your handling code here:
        pf.recommencer();
        //pf = new PanelFoot();
        haut.setEnabled(true);
       bas.setEnabled(true);
       patate.setEnabled(true);
        recommencer.setEnabled(true);
    }//GEN-LAST:event_recommencer

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Foot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Foot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Foot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Foot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
        @Override
            public void run() {
                new Foot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bas;
    private javax.swing.JButton haut;
    private javax.swing.JPanel pane;
    private javax.swing.JButton patate;
    private javax.swing.JButton recommencer;
    // End of variables declaration//GEN-END:variables
    PanelFoot pf;
}
